import { ClothingSubType } from '../types';

export const BRANDS = [
  "0'105", "100bon", "54 celsius", "7 for all mankind", "Absolut Cashmere", "Absolution", 
  "Acne Studios", "Acote", "Acquaverde", "Adidas", "Adidas Underwear", "Agnes B.", 
  "Agnes de Verneuil", "Aigle", "Albertine", "All Tigers", "Allsaints", "Allthemust", 
  "Alohas", "American Vintage", "Ami Paris", "An'ge", "Anaki", "Anatole", 
  "Ancient Greek Sandals", "Angarde", "Anonymous Copenhagen", "Ant45", "Anthology Paris", 
  "Antik Batik", "Ao76", "Apaches Collections", "Apnee", "Arizona Love", "Armani", 
  "Armani Exchange", "Armor Lux", "Arsene et les Pipelettes", "Art of Soule", "Arthur", 
  "Asics", "Aster", "Atelier Prive", "Attic and Barn", "Au Printemps Paris", 
  "Au Printemps Paris Maison", "Aubade", "Augusta", "Aurelia London", "Autre Aura", 
  "Avril Gau", "Aytm", "Ba&sh", "Babachic Bags", "Baija", "Balibaris", "Balzac Paris", 
  "Banana Moon", "Bandit", "Barbour", "Banwood", "Becksondergaard", "Bed and Philosophy", 
  "Beliza", "Bella Jones", "Bellepiece", "Bellerose", "Bensimon", "Berenice", "Billabong", 
  "Billi Bi", "Billieblush", "Billion Dollar Brows", "Billybelt", "Bimba y Lola", 
  "Bindi Atelier", "Biovive", "Birdie", "Birkenstock", "Bitossi Home", "Bjorn", 
  "Blanc d'Ivoire", "Bleuforet", "Bloomingville", "Blundstone", "Bobbi Brown", "Bobbies", 
  "Bobo Choses", "Bocage", "Bombers Original", "Bon Parfumeur", "Bonne Maison", "Bonpoint", 
  "Bons Baisers Paris", "Bonton", "Bonton Beauté", "Boob", "Born Living Yoga", "Bosabo", 
  "Boss", "Boni & Sidonie", "Burberry", "Bvlgari Parfum", "By Bar", "By Terry", 
  "Cacatoes do Brasil", "Cadet Rousselle", "Calvin Klein", "Calvin Klein Parfum", 
  "Calvin Klein Underwear", "Camalya", "Camper", "Campomaggi", "Carel Paris", "Carhartt WIP", 
  "Carioca", "Carnevale Madrid", "Caroline Najman", "Caroll", "Carpyen", "Carrement Beau", 
  "Castaner", "Caval", "Cerruti 1881 Parfum", "Chantelle", "Chantelle Pulp", "Chantelle X", 
  "Chevignon", "Chichi Castelnango", "Chie Mihara", "Chloe", "Chloe Stora", "Chlore", 
  "Christophe Robin", "Cinq Mondes", "Clae", "Clarins", "Claris Virot", "Claudie Pierlot", 
  "Claus Porto", "Clinique", "Closed", "Cloud B", "Coach", "Coco & Eve", "Collection Constance", 
  "Collectors Club", "Collegien", "Colorful Standard", "Colors of California", "Colorwow", 
  "Columbia", "Comptoir des Cotonniers", "Condor", "Converse", "Cosmoparis", "Cotelac", 
  "Couleur Pourpre", "Courtois Paris", "Craie", "Crush", "Cultiv", "Cut by Fred", "Cyrillus", 
  "D-lab Nutricosmetics", "Damson Madder", "Darphin", "David Mallett", "Davines", "Day +", 
  "Debongout", "Delbôve", "Delsey Paris", "Dermalogica", "Des Petits Hauts", "Desigual", 
  "Diadora", "Diane von Furstenberg", "Dickies", "Diega", "Diesel", "DKNY", "Dnud", "Dockers", 
  "Dolce & Gabbana", "Done by Deer", "Doran Sou", "Dr Bloom", "Dr. Hauschka", "Dr. Martens", 
  "Dragon Diffusion", "Dyson", "Eastpak", "Easy Peasy", "Eden Park", "Edwin", "Ekyog", 
  "Elemis", "Elise Chalmin", "Elizabeth Arden", "Elleme", "Emile et Ida", "Emilie Karston", 
  "Eminence", "Emzi Paris", "Enostudio", "Erborian", "Esprit", "Essentiel Antwerp", 
  "Estee Lauder", "Esthederm", "Eva Solo", "Evoked", "Fabienne Chapot", "Faconnable", 
  "Factory", "Faguo", "Falke", "Farah", "Farm Rio", "Feeka", "Fete Imperiale", "Filippa K", 
  "Filorga", "Finger in the Nose", "Flabelus", "Flotte", "Foreo", "Frame", "Frangin Frangine", 
  "Fred Perry", "Free Lance", "Frnch", "From Future", "Fusalp", "G.Kero", "Gabrielle Paris", 
  "Gamin Gamine", "Ganni", "Gant", "Garance Paris", "Gerard Darel", "Germaine des Pres", 
  "Gertrude", "Gh Bass", "Ghd", "Ghoud Venice", "Gili's", "Gina Tricot", "Ginandger", 
  "Girlfriend Collective", "Gisel B", "Givenchy", "Gola", "Goutal", "Grace et Mila", 
  "Granado", "Gucci", "Guerlain", "Guila Paris", "Hackett", "Happy Socks", "Harmony Haomy", 
  "Hartford", "Havaianas", "Hay", "Heimstone", "Helene Zubeldia", "Hello Hossy", 
  "Herbert Frere Soeur", "Herschel", "High on Love", "Hindbag", "Hipanema", "Hoff", 
  "Holidermie", "Homecore", "Hugo Boss", "Huit", "Humanoid", "Humility", "Huygens", "Hygee", 
  "I Code", "I Dig Denim", "I Talk Too Much", "Ibeliv", "Icone", "IKKS", "IKKS Junior", 
  "Il Gufo", "Image Republic", "Imperial", "Indee", "Indi & Cold", "Ines de la Fressange", 
  "Inoui Editions", "Inuikii", "Iro", "Isabel Marant", "Isabel Marant Étoile", "Jacadi", 
  "Jacquemus", "Jamini", "Jb Martin", "Jean Paul Gaultier", "Jerome Dreyfuss", 
  "John Masters Organics", "Jolibump", "Joliderm", "Jolies Momes", "Jonak", "Joone", 
  "Joseph", "Jott", "Jules & Jenn", "Juliette has a Gun", "Jordan", "K Jacques", "K-way", 
  "Karl Lagerfeld", "Karma Koma", "Kartell", "Kassandre Paris", "Kat Burki", "Kenzo", 
  "Kenzo Parfums", "Khaven", "Ki et La", "Kickers", "Kidzroom", "Kindsgut", 
  "Knowledge Cotton Apparel", "Kodanska", "Komono", "Konges Slojd", "Kookai", "Koon", 
  "Korko", "Korres", "Kosma Menorca", "Kujten", "L'atelier des Dames", "L'odaïtès", 
  "La Cerise sur le Gateau", "La Coque Francaise", "La Fee Maraboutee", "La Nouvelle", 
  "La Petite Collection", "La Petite Etoile", "La Petite Francaise", "La Sultane de Saba", 
  "Lab Dip", "Lacoste", "Lalarma", "Lamazuna", "Lancaster", "Lancaster Paris", 
  "Lancel", "Lancôme", "Laura Mercier", "Laurence Bras", "Laura Laval", "Lazartigue", 
  "Le Chat", "Le Coq en Pap'", "Le Slip Francais", "Le Tanneur", "Le Temps des Cerises", 
  "Lee", "Lelo", "Lemon Jelly", "Leon & Harper", "Leonor Greyl", "Les Deux", 
  "Les Filles en Rouje", "Les Huilettes", "Les Nereides", "Les Tropeziennes par M.Belarbi", 
  "Levi's", "Levi's Kids", "Liewood", "Lili Gaufrette", "Lison Paris", "Liu Jo", "Livia", 
  "Livy", "Livy Stone", "Lk Bennett", "Lollys Laundry", "Longchamp", "Louis Louise", 
  "Louise Misha", "Louizon", "Louvini Paris", "Love Stories", "Lucas du Tertre", 
  "Lund London", "Luz Collections", "M.A.B.E", "Made in Design Editions", "Madura", 
  "Maio Paris", "Maison 123", "Maison Doree", "Maison Hotel", "Maison Labiche", 
  "Maison Lemoine", "Maison Margiela", "Maison Minelli", "Maison Montagut", 
  "Maison Stella & Suzie", "Maison Toufet", "Maje", "Majestic Filatures", 
  "Make My Lemonade", "Mamalicious", "Manucurist", "Mapoesie", "Maradji", "Marc Jacobs", 
  "Marc O'Polo", "Margaux Lonnberg", "Marie Sixtine", "Marie-Chantal", "Martinelli Luce", 
  "Masscob", "Mat Fashion", "Max Mara Leisure", "Max Mara Week End", "Max&Co.", 
  "Mc2 Saint Barth", "Medecine Douce", "Meeko", "Mellow Yellow", "Melvin&Hamilton", 
  "Mes Demoiselles", "Mi/Mai", "Mia Zia", "Michael Kors", "Mila Louise", "Mimitika", 
  "Mini Rodini", "Minimum", "Minorquines", "Mirae", "Mkt", "Modetrotter", "Moismont", 
  "Molli", "Momoni", "Mon Precieux Gem", "Mon Shampoing", "Mon Soulier", "Moncler", 
  "Monnalisa", "Monsieur Simone", "Moon Boot", "Morgan", "Moroccanoil", "Moss Copenhagen", 
  "Most", "Mother", "Mou", "Mugler", "Musier", "Mádara", "Naguisa", "Nailmatic", 
  "Naissance Publique", "Napapijri", "Nars", "Nat & Nin", "Natalys", "Naïf", "Nenes Paris", 
  "Never Fully Dressed", "New Balance", "Newlab", "Newtone", "Nice Things", "Nike", "Nilai", 
  "Nina Ricci", "Nitah", "No Name", "Nobodinoz", "Nomadic State of Mind", "Noo", "Nooz", 
  "Noppies", "Norr", "Nuori", "O Neill", "Object", "Odaje ex. M.Moustache", "Oeuf Nyc", 
  "Olow", "Ompagnie de Californie", "On the Wild Side", "One Step", "Oof", "Opi", "Oribe", 
  "Original Mineral", "Origins", "Orta", "Oyoy Living Design", "Oolution", "P448", "Pablo", 
  "Paco Rabanne", "Pai Skincare", "Paloma Collection", "Palomitas by Paloma Barcelo", 
  "Panier des Sens", "Parisienne et Alors", "Passionata", "Patagonia", "Patyka", 
  "Paul and Joe", "Paul Bertin Paris", "Paul Smith", "Paule Ka", "Payot", "Pennyblack", 
  "Pepe Jeans", "Perricone Md", "Persona by Marina Rinaldi", "Peter Thomas Roth", 
  "Petit Bateau", "Petit Pan", "Petite Lucette", "Petite Mendigote", "Pieces", 
  "Pink Stories", "Pinko", "Piquadro", "Please", "Polaar", "Polina", "Polo Ralph Lauren", 
  "Pols Potten", "Pomandere", "Pomponne", "Portuguese Flannel", "Potiron Paris", "Pourchet", 
  "Prada", "Puissante", "Puma", "Pyrenex", "Qiriness", "Raawii", "Rahua", "Rails", "Rains", 
  "Ralph Lauren Home", "Re.sea", "Re/done", "Redskins", "Reebok", "Reformation", "Reiko", 
  "Rejeanne", "Ren Skincare", "Repetto", "Reqins", "Rita Row", "Rituals", "Rive Droite Paris", 
  "Rivecour", "Robeez", "Robin Collection", "Rodier", "Roll on Jade", "Rosae Paris", 
  "Rose in April", "Roseanna", "Rotate", "Rouge Edit", "Rouje", "Royalties", "Rue de Tokyo", 
  "Sabon", "Sabots Youyou", "Sachajuan", "Sack S", "Saint James", "Saison 1865", 
  "Sam Edelman", "Samsoe Samsoe", "Sandro", "Sans Arcidet", "Saona", "Satellite Paris", 
  "Saucony", "Schmoove", "Scholl", "Schott", "Scotch and Soda", "Sebago", "Second Female", 
  "See by Chloe", "See u Soon", "Selected", "Seletti", "Self Portrait", "Semerdjian - Smr", 
  "Septem", "Seraphine", "Serax", "Serge Blanco", "Sessun", "Sezane", "Shiseido", 
  "Sir Edward", "Slide", "Sliwils", "Smoon", "Socque Paris", "Soeur", "Soi Paris", 
  "Sonia Rykiel", "Sophie+Lucie", "Sorel", "Soulier Martinez", "Sowden", "Sowe Biarritz", 
  "Staud", "Stella Forest", "Stella Nova", "Stella Pardo", "Studio Boheme", "Sud Express", 
  "Sunchild", "Suncoo", "Sundek", "Sundress", "Superdry", "Superga", "Supermom", "Surprise", 
  "Suzie Winkle", "Swarovski", "Sweet Pants", "Swildens", "Swim Essentials", "Taion", 
  "Tamaris", "Tammy & Benjamin", "Tangent", "Tara Jarmon", "Tartine et Chocolat", 
  "The Animals Observatory", "The Campamento", "The Elf on the Shelf", "The Kooples", 
  "The Korner", "The Label Edition", "The Line", "The New Society", "The Tiny Big Sister", 
  "Theory", "Thinking Mu", "Timberland", "Tinsels", "Tinycottons", "Toasties", 
  "Today Linge de Maison", "Tommy Hilfiger", "Topologie", "Trixie", "Twinset", "Ugg", 
  "Undress Code", "Une a Une", "V de Vinster", "Valentine Gauthier", "Vanessa Baroni", 
  "Vanessa Bruno", "Vanessa Seward", "Vanessa Wu", "Vans", "Varley", "Veja", 
  "Vendredi Swimwear", "Vero Moda Curve", "Victoria", "Vila", "Vilebrequin", "Wella", 
  "Wild", "Wild & Gorgeous", "Wild Science Lab", "Wolford", "Womanizer", "Yas", "Yay", 
  "Yesforlov", "Yoga Searcher", "Yuj Yoga Paris", "Yves Saint Laurent", "Zadig&Voltaire", 
  "Zapa", "Zespa", "Wedo"
];

export type ColorType = {
  id: string;
  value: string;
}

export const COLORS: ColorType[] = [
  { id: 'black', value: '#000000' },
  { id: 'gray', value: '#808080' },
  { id: 'silver', value: '#C0C0C0' },
  { id: 'white', value: '#FFFFFF' },
  { id: 'beige', value: '#F5F5DC' },
  { id: 'blue', value: '#0000FF' },
  { id: 'navy', value: '#35358d' },
  { id: 'light-blue', value: '#89cff0' },
  { id: 'red', value: '#FF0000' },
  { id: 'burgundy', value: '#ae2e3d' },
  { id: 'pink', value: '#FFC0CB' },
  { id: 'violet', value: '#800080' },
  { id: 'lilac', value: '#d297d2' },
  { id: 'gold', value: '#FFD700' },
  { id: 'yellow', value: '#FFFF00' },
  { id: 'mustard', value: '#e5b539' },
  { id: 'mint', value: '#a2ffbc' },
  { id: 'green', value: '#00FF00' },
  { id: 'forest-green', value: '#2d6c3e' },
  { id: 'kaki', value: '#94812b' },
  { id: 'brown', value: '#A52A2A' },
  { id: 'orange', value: '#FFA500' },
  { id: 'abricot', value: '#ffcc98' },
  { id: 'multicolor', value: 'linear-gradient' },
];

export const fits: { [key: string]: string } = {
    'slim': 'Slim',
    'regular': 'Regular',
    'loose': 'Loose',
    'oversize': 'Oversize'
  };

export const types: { [key: string]: string } = {
    'top': 'Haut',
    'bottom': 'Bas',
    'shoes': 'Chaussures',
    'accessory': 'Accessoire',
    'ensemble': 'Ensemble'
  };

export const subtypesByType: { [key: string]: { [key in ClothingSubType]?: string } } = {
  'top': {
    'tshirt': 'T-shirt',
    'polo': 'Polo',
    'shirt': 'Chemise',
    'sweater': 'Pull',
    'sweatshirt': 'Sweat',
    'jacket': 'Veste',
    'coat': 'Manteau',
    'blazer': 'Blazer'
  },
  'bottom': {
    'jeans': 'Jean',
    'pants': 'Pantalon',
    'shorts': 'Short',
    'skirt': 'Jupe',
    'sweatpants': 'Jogging',
  },
  'shoes': {
    'sneakers': 'Baskets',
    'boots': 'Bottes',
    'flats': 'Tennis',
    'heels': 'Talons',
    'dress_shoes': 'Chaussures de ville',
    'sandals': 'Sandales',
    'mocassin': 'Mocassin',
    'hoof': 'Sabot',
    'slipper': 'Chaussons',
  },
  'accessory': {
    'hat': 'Chapeau',
    'scarf': 'Écharpe',
    'belt': 'Ceinture',
    'bag': 'Sac',
    'socks': 'Chaussettes',
    'jewelry': 'Bijoux',
    'watch': 'Montre',
    'glasses': 'Lunettes',
    'nylon': 'Collants'
  },
  'ensemble': {
    'dress': 'Robe',
    'jumpsuit': 'Combinaison',
    'suit': 'Costume',
    'overalls': 'Salopette'
  }
};

export const PATTERNS = {
  cashmere: 'Cachemire',
  camouflage: 'Camouflage',
  plaid_and_tartan: 'Carreaux et tartan',
  ombre: 'Ombre',
  floral: 'Fleuri',
  animal_print: 'Imprimé animal',
  graphics_and_logos: 'Graphismes et logos',
  houndstooth: 'Pied-de-poule',
  polka_dots: 'Pois',
  stripes: 'Rayures',
  tie_dye: 'Tie-dye',
  plain: 'Uni',
  zig_zag: 'Zig-zag',
  patchwork: 'Patchwork',
  topstitching: 'Couture apparente',
} as const;

export type Pattern = typeof PATTERNS[keyof typeof PATTERNS];