export const MATERIALS: { [key: string]: string } = {
  "acrylic": "Acrylique",
  "alpaca": "Alpaga",
  "bamboo": "Bambou",
  "canvas": "Toile",
  "cardboard": "Carton",
  "cashmere": "Cachemire",
  "ceramic": "Céramique",
  "chiffon": "Mousseline",
  "corduroy": "Velours côtelé",
  "cotton": "Coton",
  "denim": "Denim",
  "down": "Duvet",
  "elastane": "Élasthanne",
  "faux fur": "Fausse fourrure",
  "faux leather": "Simili cuir",
  "felt": "Feutre",
  "flannel": "Flanelle",
  "fleece": "Polaire",
  "foam": "Mousse",
  "glass": "Verre",
  "gold": "Or",
  "jute": "Jute",
  "lace": "Dentelle",
  "latex": "Latex",
  "leather": "Cuir",
  "linen": "Lin",
  "merino": "Mérinos",
  "mesh": "Maille",
  "metal": "Métal",
  "mohair": "Mohair",
  "neoprene": "Néoprène",
  "nylon": "Nylon",
  "paper": "Papier",
  "patent leather": "Cuir verni",
  "plastic": "Plastique",
  "polyester": "Polyester",
  "porcelain": "Porcelaine",
  "rattan": "Rotin",
  "rubber": "Caoutchouc",
  "satin": "Satin",
  "sequin": "Paillettes",
  "silicone": "Silicone",
  "silk": "Soie",
  "silver": "Argent",
  "steel": "Acier",
  "stone": "Pierre",
  "straw": "Paille",
  "suede": "Daim",
  "tulle": "Tulle",
  "tweed": "Tweed",
  "velour": "Velours",
  "velvet": "Velours",
  "viscose": "Viscose",
  "wood": "Bois",
  "wool": "Laine"
}; 