export const occasions: { [key: string]: string } = {
  "classic": "Classique",
  "minimalist": "Minimaliste",
  "bohemian": "Bohème",
  "rock": "Rock",
  "punk": "Punk",
  "gothic": "Gothique",
  "streetwear": "Streetwear",
  "sportswear": "Sportswear",
  "preppy": "Preppy",
  "casual": "Casual",
  "vintage": "Vintage",
  "arty": "Arty",
  "glamorous": "Glamour",
  "fashionista": "Fashionista",
  "hipster": "Hipster",
  "western": "Western",
  "ethnic": "Ethnique",
  "gypset": "Gypset",
  "coachella": "Coachella",
  "utilitywear": "Utilitywear",
  "loungewear": "Loungewear",
  "athleisure": "Athleisure",
  "urbanchic": "Urban chic",
  "modern": "Moderne",
  "formal": "Formelle",
  "dandy": "Dandy",
  "military": "Militaire",
  "nautical": "Nautique",
  "safari": "Safari",
  "skatewear": "Skateur",
  "surfer": "Surfeur",
  "country": "Country",
  "kawaii": "Kawaii",
  "lolita": "Lolita",
  "harajuku": "Harajuku",
  "y2k": "Y2K",
  "steampunk": "Steampunk",
  "futuristic": "Futuriste",
  "monochrome": "Monochrome",
  "tailoring": "Tailoring",
  "riviera": "Riviera",
  "normcore": "Normcore"
};

export const seasons: { [key: string]: string } = {
  'all': 'all',
  'spring': 'spring',
  'summer': 'summer',
  'fall': 'fall',
  'winter': 'winter'
};

export const genders: { [key: string]: string } = {
  'male': 'male',
  'female': 'female',
  'unisex': 'unisex'
};

export const STYLES = [
  { id: 'arty', image: require('@/assets/images/styles/arty.jpg') },
  { id: 'athleisure', image: require('@/assets/images/styles/athleisure.jpg') },
  { id: 'bohemian', image: require('@/assets/images/styles/bohemian.jpg') },
  { id: 'casual', image: require('@/assets/images/styles/casual.jpg') },
  { id: 'coachella', image: require('@/assets/images/styles/coachella.jpg') },
  { id: 'country', image: require('@/assets/images/styles/country.jpg') },
  { id: 'dandy', image: require('@/assets/images/styles/dandy.jpg') },
  { id: 'ethnic', image: require('@/assets/images/styles/ethnic.jpg') },
  { id: 'fashionista', image: require('@/assets/images/styles/fashionista.jpg') },
  { id: 'formal', image: require('@/assets/images/styles/formal.jpg') },
  { id: 'futuristic', image: require('@/assets/images/styles/futuristic.jpg') },
  { id: 'glamorous', image: require('@/assets/images/styles/glamorous.jpg') },
  { id: 'gothic', image: require('@/assets/images/styles/gothic.jpg') },
  { id: 'harajuku', image: require('@/assets/images/styles/harajuku.jpg') },
  { id: 'hipster', image: require('@/assets/images/styles/hipster.jpg') },
  { id: 'kawaii', image: require('@/assets/images/styles/kawaii.jpg') },
  { id: 'lolita', image: require('@/assets/images/styles/lolita.jpg') },
  { id: 'loungewear', image: require('@/assets/images/styles/loungewear.jpg') },
  { id: 'military', image: require('@/assets/images/styles/military.jpg') },
  { id: 'minimalist', image: require('@/assets/images/styles/minimalist.jpg') },
  { id: 'modern', image: require('@/assets/images/styles/modern.jpg') },
  { id: 'monochrome', image: require('@/assets/images/styles/monochrome.jpg') },
  { id: 'normcore', image: require('@/assets/images/styles/normcore.jpg') },
  { id: 'preppy', image: require('@/assets/images/styles/preppy.jpg') },
  { id: 'punk', image: require('@/assets/images/styles/punk.jpg') },
  { id: 'riviera', image: require('@/assets/images/styles/riviera.jpg') },
  { id: 'rock', image: require('@/assets/images/styles/rock.jpg') },
  { id: 'safari', image: require('@/assets/images/styles/safari.jpg') },
  { id: 'skatewear', image: require('@/assets/images/styles/skatewear.jpg') },
  { id: 'sportwear', image: require('@/assets/images/styles/sportwear.jpg') },
  { id: 'steampunk', image: require('@/assets/images/styles/steampunk.jpg') },
  { id: 'streetwear', image: require('@/assets/images/styles/streetwear.jpg') },
  { id: 'surfer', image: require('@/assets/images/styles/surfer.jpg') },
  { id: 'tailoring', image: require('@/assets/images/styles/tailoring.jpg') },
  { id: 'urbanchic', image: require('@/assets/images/styles/urbanchic.jpg') },
  { id: 'utilitywear', image: require('@/assets/images/styles/utilitywear.jpg') },
  { id: 'vintage', image: require('@/assets/images/styles/vintage.jpg') },
  { id: 'western', image: require('@/assets/images/styles/western.jpg') },
  { id: 'y2k', image: require('@/assets/images/styles/y2k.jpg') },
];