export const occasions: { [key: string]: string } = {
  "classic": "Classique",
  "minimalist": "Minimaliste",
  "bohemian": "Bohème",
  "rock": "Rock",
  "punk": "Punk",
  "gothic": "Gothique",
  "streetwear": "Streetwear",
  "sportswear": "Sportswear",
  "preppy": "Preppy",
  "casual": "Casual",
  "vintage": "Vintage",
  "arty": "Arty",
  "glamorous": "Glamour",
  "fashionista": "Fashionista",
  "hipster": "Hipster",
  "western": "Western",
  "ethnic": "Ethnique",
  "gypset": "Gypset",
  "coachella": "Coachella",
  "utilitywear": "Utilitywear",
  "loungewear": "Loungewear",
  "athleisure": "Athleisure",
  "urbanchic": "Urban chic",
  "modern": "Moderne",
  "formal": "Formelle",
  "dandy": "Dandy",
  "military": "Militaire",
  "nautical": "Nautique",
  "safari": "Safari",
  "skatewear": "Skateur",
  "surfer": "Surfeur",
  "country": "Country",
  "kawaii": "Kawaii",
  "lolita": "Lolita",
  "harajuku": "Harajuku",
  "y2k": "Y2K",
  "steampunk": "Steampunk",
  "futuristic": "Futuriste",
  "monochrome": "Monochrome",
  "tailoring": "Tailoring",
  "riviera": "Riviera",
  "normcore": "Normcore"
};

export const seasons: { [key: string]: string } = {
  'all': 'Toutes les saisons',
  'spring': 'Printemps',
  'summer': 'Été',
  'fall': 'Automne',
  'winter': 'Hiver'
};

export const genders: { [key: string]: string } = {
  'male': 'Homme',
  'female': 'Femme',
  'unisex': 'Unisexe'
};

export const STYLES = [
  { id: 'arty', name: 'Artistique', image: require('@/assets/images/styles/arty.jpg') },
  { id: 'athleisure', name: 'Athleisure', image: require('@/assets/images/styles/athleisure.jpg') },
  { id: 'bohemian', name: 'Bohème', image: require('@/assets/images/styles/bohemian.jpg') },
  { id: 'casual', name: 'Casual', image: require('@/assets/images/styles/casual.jpg') },
  { id: 'coachella', name: 'Coachella', image: require('@/assets/images/styles/coachella.jpg') },
  { id: 'country', name: 'Country', image: require('@/assets/images/styles/country.jpg') },
  { id: 'dandy', name: 'Dandy', image: require('@/assets/images/styles/dandy.jpg') },
  { id: 'ethnic', name: 'Ethnique', image: require('@/assets/images/styles/ethnic.jpg') },
  { id: 'fashionista', name: 'Fashionista', image: require('@/assets/images/styles/fashionista.jpg') },
  { id: 'formal', name: 'Formel', image: require('@/assets/images/styles/formal.jpg') },
  { id: 'futuristic', name: 'Futuriste', image: require('@/assets/images/styles/futuristic.jpg') },
  { id: 'glamorous', name: 'Glamour', image: require('@/assets/images/styles/glamorous.jpg') },
  { id: 'gothic', name: 'Gothique', image: require('@/assets/images/styles/gothic.jpg') },
  { id: 'harajuku', name: 'Harajuku', image: require('@/assets/images/styles/harajuku.jpg') },
  { id: 'hipster', name: 'Hipster', image: require('@/assets/images/styles/hipster.jpg') },
  { id: 'kawaii', name: 'Kawaii', image: require('@/assets/images/styles/kawaii.jpg') },
  { id: 'lolita', name: 'Lolita', image: require('@/assets/images/styles/lolita.jpg') },
  { id: 'loungewear', name: 'Loungewear', image: require('@/assets/images/styles/loungewear.jpg') },
  { id: 'military', name: 'Militaire', image: require('@/assets/images/styles/military.jpg') },
  { id: 'minimalist', name: 'Minimaliste', image: require('@/assets/images/styles/minimalist.jpg') },
  { id: 'modern', name: 'Moderne', image: require('@/assets/images/styles/modern.jpg') },
  { id: 'monochrome', name: 'Monochrome', image: require('@/assets/images/styles/monochrome.jpg') },
  { id: 'normcore', name: 'Normcore', image: require('@/assets/images/styles/normcore.jpg') },
  { id: 'preppy', name: 'Preppy', image: require('@/assets/images/styles/preppy.jpg') },
  { id: 'punk', name: 'Punk', image: require('@/assets/images/styles/punk.jpg') },
  { id: 'riviera', name: 'Riviera', image: require('@/assets/images/styles/riviera.jpg') },
  { id: 'rock', name: 'Rock', image: require('@/assets/images/styles/rock.jpg') },
  { id: 'safari', name: 'Safari', image: require('@/assets/images/styles/safari.jpg') },
  { id: 'skatewear', name: 'Skatewear', image: require('@/assets/images/styles/skatewear.jpg') },
  { id: 'sportwear', name: 'Sportwear', image: require('@/assets/images/styles/sportwear.jpg') },
  { id: 'steampunk', name: 'Steampunk', image: require('@/assets/images/styles/steampunk.jpg') },
  { id: 'streetwear', name: 'Streetwear', image: require('@/assets/images/styles/streetwear.jpg') },
  { id: 'surfer', name: 'Surfer', image: require('@/assets/images/styles/surfer.jpg') },
  { id: 'tailoring', name: 'Tailoring', image: require('@/assets/images/styles/tailoring.jpg') },
  { id: 'urbanchic', name: 'Urban Chic', image: require('@/assets/images/styles/urbanchic.jpg') },
  { id: 'utilitywear', name: 'Utility Wear', image: require('@/assets/images/styles/utilitywear.jpg') },
  { id: 'vintage', name: 'Vintage', image: require('@/assets/images/styles/vintage.jpg') },
  { id: 'western', name: 'Western', image: require('@/assets/images/styles/western.jpg') },
  { id: 'y2k', name: 'Y2K', image: require('@/assets/images/styles/y2k.jpg') },
];